export const WORLD_ROUTES = Object.freeze({
  ORDER_TO_SUPPLIER:["COMMERCE_CITY","SUPPLIER"],
  MARKETING_REQUEST:["COMMERCE_CITY","MARKETING"],
  MARKETING_TO_FACTORY:["MARKETING","DARK_FACTORY"],
  FACTORY_TO_MARKETING:["DARK_FACTORY","MARKETING"],
  MARKETING_TO_CHANNEL:["MARKETING","CHANNEL"],
  CUSTOMER_TO_ORDER:["CHANNEL","ATTENDANT","COMMERCE_CITY","ORDER"]
});